import { SEOHead, SEO_CONFIG } from "@/components/SEOHead";
import { Link } from "wouter";
import { ChevronDown, ChevronUp, ArrowLeft } from "lucide-react";
import { useState } from "react";

// Google Rich Results compliant FAQPage schema
// Follows: https://developers.google.com/search/docs/appearance/structured-data/faqpage
const faqSchema = {
  "@context": "https://schema.org",
  "@type": "FAQPage",
  mainEntity: [
    {
      "@type": "Question",
      name: "What is STS Futures?",
      acceptedAnswer: {
        "@type": "Answer",
        text: "STS Futures is a systematic NQ (Nasdaq-100 E-mini) futures trading signals platform. It provides real-time intraday trade alerts generated by a rules-based algorithm with a verified 15-year backtest spanning 2011–2026. Subscribers get full access to the web dashboard, trade history, equity curves, and risk analytics.",
      },
    },
    {
      "@type": "Question",
      name: "What is the track record of the NQ strategy?",
      acceptedAnswer: {
        "@type": "Answer",
        text: "The NQ Triple Variant strategy has a 15-year backtested track record (2011–2026) showing a +1,085% total return on a $10,000 starting account, a 45.9% win rate, a Sharpe ratio of 1.05 (Sortino 1.22), and a maximum drawdown of approximately 51%. Every trade — wins and losses — is visible in the dashboard. Past performance is not indicative of future results.",
      },
    },
    {
      "@type": "Question",
      name: "How are trading signals delivered?",
      acceptedAnswer: {
        "@type": "Answer",
        text: "Signals are delivered in two ways: (1) Real-time alerts on the STS Futures web dashboard — a notification appears the moment the algorithm fires a trade entry or exit. (2) Email alerts — subscribers can enable email notifications in their account preferences to receive an email whenever a new signal is generated.",
      },
    },
    {
      "@type": "Question",
      name: "What markets and instruments does STS Futures cover?",
      acceptedAnswer: {
        "@type": "Answer",
        text: "STS Futures currently focuses exclusively on NQ (Nasdaq-100 E-mini) futures contracts traded on the CME. The strategy is an intraday system, meaning all positions are entered and exited within the same trading session — no overnight holds.",
      },
    },
    {
      "@type": "Question",
      name: "How much does a subscription cost?",
      acceptedAnswer: {
        "@type": "Answer",
        text: "The STS Futures Pro Plan is $50 per month. There is no free trial. You get immediate full access upon subscribing. You can cancel anytime from your account settings — your access continues until the end of the current billing period. All sales are final.",
      },
    },
    {
      "@type": "Question",
      name: "Is STS Futures suitable for beginners?",
      acceptedAnswer: {
        "@type": "Answer",
        text: "STS Futures is best suited for traders who already understand how futures contracts work and are comfortable with the risks involved. The dashboard includes a paper trading mode that lets you follow signals without risking real capital, which is a good starting point. However, trading NQ futures involves substantial risk of loss and is not appropriate for all investors.",
      },
    },
    {
      "@type": "Question",
      name: "Do I need a specific broker to use the signals?",
      acceptedAnswer: {
        "@type": "Answer",
        text: "No specific broker is required. STS Futures delivers signals via the dashboard and email — you execute trades manually through any futures broker that supports NQ contracts (e.g., NinjaTrader, Interactive Brokers, TradeStation, Tradovate). The Broker Setup guide in the dashboard walks through the configuration for supported platforms.",
      },
    },
    {
      "@type": "Question",
      name: "What is the refund policy?",
      acceptedAnswer: {
        "@type": "Answer",
        text: "All sales are final. No refunds are issued for partial billing periods. You can cancel your subscription at any time from your account settings, and your access will remain active until the end of the current billing cycle.",
      },
    },
  ],
};

// BreadcrumbList schema is injected server-side by prerenderMiddleware

interface FAQItemProps {
  question: string;
  answer: string;
  index: number;
}

function FAQItem({ question, answer, index }: FAQItemProps) {
  const [open, setOpen] = useState(index === 0); // First item open by default

  return (
    <div className="border border-border rounded-lg overflow-hidden">
      <button
        className="w-full flex items-center justify-between px-5 py-4 text-left bg-card hover:bg-muted/40 transition-colors focus:outline-none focus-visible:ring-2 focus-visible:ring-primary"
        onClick={() => setOpen(!open)}
        aria-expanded={open}
      >
        <span className="font-semibold text-foreground pr-4">{question}</span>
        {open ? (
          <ChevronUp className="h-5 w-5 text-muted-foreground flex-shrink-0" />
        ) : (
          <ChevronDown className="h-5 w-5 text-muted-foreground flex-shrink-0" />
        )}
      </button>
      {open && (
        <div className="px-5 py-4 bg-card border-t border-border">
          <p className="text-muted-foreground leading-relaxed">{answer}</p>
        </div>
      )}
    </div>
  );
}

export default function FAQ() {
  return (
    <>
      <SEOHead {...SEO_CONFIG.qa} />
      {/* Structured data is injected server-side by prerenderMiddleware to avoid duplicates */}

      <div className="min-h-screen bg-background">
        {/* Header */}
        <div className="border-b border-border/50">
          <div className="container py-4">
            <div className="flex items-center justify-between">
              <Link
                href="/"
                className="flex items-center gap-2 text-sm text-muted-foreground hover:text-foreground transition-colors"
              >
                <ArrowLeft className="h-4 w-4" />
                Back to Home
              </Link>
              <Link
                href="/pricing"
                className="text-sm font-medium text-primary hover:underline"
              >
                View Pricing →
              </Link>
            </div>
          </div>
        </div>

        {/* Hero */}
        <div className="container py-12 md:py-16 text-center">
          <nav aria-label="Breadcrumb" className="mb-6">
            <ol className="flex items-center justify-center gap-2 text-sm text-muted-foreground">
              <li>
                <Link
                  href="/"
                  className="hover:text-foreground transition-colors"
                >
                  Home
                </Link>
              </li>
              <li aria-hidden="true">/</li>
              <li className="text-foreground font-medium" aria-current="page">
                FAQ
              </li>
            </ol>
          </nav>
          <h1 className="text-3xl md:text-4xl font-bold text-foreground mb-4">
            Frequently Asked Questions
          </h1>
          <p className="text-lg text-muted-foreground max-w-2xl mx-auto">
            Everything you need to know about STS Futures, our NQ trading
            signals, and how the platform works.
          </p>
        </div>

        {/* FAQ Accordion */}
        <div className="container pb-16 max-w-3xl">
          <div className="space-y-3">
            {faqSchema.mainEntity.map((item, i) => (
              <FAQItem
                key={i}
                index={i}
                question={item.name}
                answer={item.acceptedAnswer.text}
              />
            ))}
          </div>

          {/* CTA */}
          <div className="mt-12 p-6 rounded-xl border border-border bg-card text-center">
            <h2 className="text-xl font-semibold text-foreground mb-2">
              Still have questions?
            </h2>
            <p className="text-muted-foreground mb-4">
              Have a question not answered here? Reach out via the contact form
              on the homepage.
            </p>
            <div className="flex flex-col sm:flex-row gap-3 justify-center">
              <Link
                href="/pricing"
                className="inline-flex items-center justify-center rounded-md bg-primary text-primary-foreground px-6 py-2.5 text-sm font-medium hover:bg-primary/90 transition-colors"
              >
                View Pricing
              </Link>
              <Link
                href="/"
                className="inline-flex items-center justify-center rounded-md border border-border bg-background px-6 py-2.5 text-sm font-medium hover:bg-muted transition-colors"
              >
                Back to Home
              </Link>
            </div>
          </div>

          {/* Risk disclaimer */}
          <p className="mt-8 text-xs text-muted-foreground text-center leading-relaxed">
            Trading futures involves substantial risk of loss and is not
            appropriate for all investors. Past performance is not indicative of
            future results. The information on this site is for informational
            purposes only and does not constitute financial advice.{" "}
            <Link
              href="/risk-disclosure"
              className="underline hover:text-foreground transition-colors"
            >
              Full Risk Disclosure
            </Link>
          </p>
        </div>
      </div>
    </>
  );
}
