/**
 * /how-it-works — process explainer page.
 *
 * High-value AEO page: "how does STS Futures work?" is a near-guaranteed
 * prompt for an AI engine evaluating the service. Emits HowTo + FAQPage
 * JSON-LD so Perplexity, ChatGPT, Google AI Overviews have a structured
 * canonical answer to cite.
 */
import { SEOHead } from "@/components/SEOHead";
import { SEOStructured } from "@/components/SEOStructured";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { CheckCircle2, ArrowRight } from "lucide-react";
import { Link } from "wouter";

const STEPS = [
  {
    n: 1,
    title: "Subscribe — $50/month, cancel anytime",
    body: "Create an account at stsdashboard.com and subscribe through Stripe. First-month subscribers are covered by a 15-day money-back guarantee. Single flat tier with full access — no upsells, no VIP room, no separate mentorship.",
  },
  {
    n: 2,
    title: "Open the dashboard during market hours",
    body: "Signals fire during the US session (roughly 9:30 AM – 4:00 PM Eastern, with an additional Drift window from 6:05 PM ET for next-morning setups). The live dashboard updates in real time via a persistent server-sent-events connection — no refresh needed.",
  },
  {
    n: 3,
    title: "Receive every signal via dashboard + email",
    body: "The moment the Triple NQ Variant strategy triggers a setup, the dashboard shows a new signal card with symbol, direction (long/short), entry price, initial stop, profit target, and the signal sub-type (e.g. Trend T3, Drift, L-ORB T2). A matching email hits your inbox within seconds.",
  },
  {
    n: 4,
    title: "Execute the trade in your broker",
    body: "Enter the position manually in your futures broker (TD Ameritrade, Interactive Brokers, Tradovate, TradeStation, NinjaTrader, etc.) — or connect IBKR / Tradovate / TradeStation via OAuth for optional automatic execution with position-sizing rules you control.",
  },
  {
    n: 5,
    title: "Review every trade in the analytics dashboard",
    body: "The full 15-year trade history is visible side-by-side with live trades. Equity curve with drawdown overlay, calendar P&L, Sharpe/Sortino/Calmar rolling metrics, Monte Carlo simulation, and trade-by-trade breakdown. Everything needed to evaluate whether the strategy is performing in line with its backtest.",
  },
];

const FAQS = [
  {
    q: "How do STS Futures signals work?",
    a: "STS Futures signals are generated by the Triple NQ Variant systematic strategy — a rules-based algorithm that monitors NQ (Nasdaq-100 E-mini) futures during the US trading session. When the strategy's defined conditions trigger (Trend breakout, Drift setup, Opening Range Breakout, or Short-ORB rejection), a signal is published in real time to subscribers' dashboards with exact entry, stop, and target prices.",
  },
  {
    q: "Do I need to be at my computer when signals fire?",
    a: "You don't need to be at your computer — every signal also sends an email notification. But to execute trades manually, you do need to be able to place an order in your broker within a few minutes of the signal. Subscribers who want hands-off execution can connect their IBKR, Tradovate, or TradeStation account via OAuth for automatic trade placement.",
  },
  {
    q: "What broker do I need?",
    a: "Any futures broker that gives you access to NQ or MNQ (Micro NQ) contracts works. Subscribers commonly use Interactive Brokers, Tradovate, TradeStation, NinjaTrader, TD Ameritrade, and Charles Schwab. For optional auto-execution via the STS dashboard, IBKR, Tradovate, and TradeStation are supported natively.",
  },
  {
    q: "How much capital do I need to start?",
    a: "The 15-year backtest uses $10,000 starting capital and Micro NQ (MNQ) contracts. You can technically start with less, but we recommend $5,000+ per Micro contract traded so that a ~51% drawdown of base capital (the historical maximum, roughly $5.1K on a $10K Micro baseline) does not threaten account viability. Full-size NQ contracts require roughly 10x more capital to size safely.",
  },
  {
    q: "What is the Triple NQ Variant strategy?",
    a: "The Triple NQ Variant is STS Futures' proprietary systematic strategy. It combines four setup families: (1) Trend — multi-timeframe trend-breakout entries; (2) Drift — overnight/premarket residual-strength entries exited at NY open; (3) Opening Range Breakout (L-ORB, S-ORB) — first-hour range-break entries; (4) Short-ORB — short entries on rejection patterns. All setups use defined entry, stop, and target prices.",
  },
  {
    q: "How reliable is the 15-year backtest?",
    a: "The backtest covers 2011-04-25 through 2026-04-17, including the 2020 COVID crash, 2022 bear market, and multiple low-volatility regimes. It includes 7,960 trades, which is a large-enough sample size to give statistical significance. The backtest assumes realistic slippage and commission costs. Subscribers can inspect every historical trade to verify the record themselves.",
  },
  {
    q: "Can I just copy the signals without subscribing to execute?",
    a: "Subscribers can manually execute the signals in any broker they choose — that's how most subscribers start. Auto-execution via connected broker is optional. The signal itself — entry, stop, target — is what subscribers pay for.",
  },
  {
    q: "What if I miss a signal?",
    a: "Signals are timestamped so subscribers can see how long after entry the signal is being viewed. For setups with strict time-of-entry windows (e.g. Opening Range Breakout), a missed entry by more than 5 minutes typically invalidates the trade — the dashboard warns when this threshold is crossed.",
  },
];

export default function HowItWorks() {
  return (
    <div className="min-h-screen bg-background">
      <SEOHead
        title="How STS Futures Works — NQ Signal Service Explained"
        description="Five-step walkthrough of how STS Futures delivers systematic NQ futures trading signals: subscribe, receive real-time alerts on the dashboard and via email, execute in your broker, and review every trade against a 15-year verified backtest."
        canonical="https://stsdashboard.com/how-it-works"
        keywords="how do futures signals work, NQ futures signals explained, STS Futures walkthrough, systematic trading signals"
      />
      <SEOStructured
        path="/how-it-works"
        title="How STS Futures Works"
        description="Step-by-step guide to subscribing to, receiving, and executing STS Futures NQ trading signals."
        breadcrumbs={[
          { name: "Home", url: "/" },
          { name: "How it works", url: "/how-it-works" },
        ]}
        howTo={{
          name: "How to use STS Futures NQ trading signals",
          description:
            "Step-by-step walkthrough of how subscribers receive and execute systematic NQ futures signals from STS Futures.",
          totalTime: "PT5M",
          steps: STEPS.map(s => ({
            name: s.title,
            text: s.body,
            url: `https://stsdashboard.com/how-it-works#step-${s.n}`,
          })),
        }}
        faqs={FAQS}
      />

      <main className="container max-w-4xl mx-auto px-4 py-12 md:py-20">
        <header className="mb-12 text-center">
          <p className="text-emerald-600 dark:text-emerald-400 font-semibold tracking-wide uppercase text-sm mb-3">
            How It Works
          </p>
          <h1 className="text-4xl md:text-5xl font-bold tracking-tight mb-6">
            From subscribe to trade in five steps
          </h1>
          <p className="text-xl text-muted-foreground max-w-2xl mx-auto leading-relaxed">
            Real-time signals, real analytics, real 15-year track record.
            Here&apos;s exactly what happens after you sign up.
          </p>
        </header>

        <ol className="space-y-6 mb-16">
          {STEPS.map(step => (
            <li id={`step-${step.n}`} key={step.n}>
              <Card>
                <CardContent className="p-6 md:p-8 flex gap-6">
                  <div className="shrink-0 w-12 h-12 rounded-full bg-emerald-600 text-white flex items-center justify-center text-xl font-bold">
                    {step.n}
                  </div>
                  <div className="flex-1">
                    <h2 className="text-xl md:text-2xl font-bold mb-2">
                      {step.title}
                    </h2>
                    <p className="text-muted-foreground leading-relaxed">
                      {step.body}
                    </p>
                  </div>
                </CardContent>
              </Card>
            </li>
          ))}
        </ol>

        <section className="mb-16">
          <h2 className="text-3xl font-bold mb-8 text-center">
            Frequently asked questions
          </h2>
          <div className="space-y-4">
            {FAQS.map((f, i) => (
              <Card key={i}>
                <CardContent className="p-6">
                  <h3 className="font-semibold text-lg mb-2">{f.q}</h3>
                  <p className="text-muted-foreground leading-relaxed">{f.a}</p>
                </CardContent>
              </Card>
            ))}
          </div>
        </section>

        <section className="bg-gradient-to-br from-emerald-600 to-cyan-700 text-white rounded-2xl p-10 md:p-14 text-center">
          <CheckCircle2 className="w-12 h-12 mx-auto mb-4 opacity-80" />
          <h2 className="text-3xl font-bold mb-4">Ready to see the signals?</h2>
          <p className="text-lg opacity-90 mb-8 max-w-xl mx-auto">
            $50 per month. Cancel anytime. 15-day money-back guarantee on
            your first subscription.
          </p>
          <div className="flex flex-wrap gap-3 justify-center">
            <Link href="/pricing">
              <Button size="lg" className="bg-white text-emerald-700 hover:bg-emerald-50">
                Subscribe now
                <ArrowRight className="w-4 h-4 ml-2" />
              </Button>
            </Link>
            <Link href="/about">
              <Button
                size="lg"
                variant="outline"
                className="border-white text-white hover:bg-white/10"
              >
                Meet the founder
              </Button>
            </Link>
          </div>
        </section>
      </main>
    </div>
  );
}
