import { Button } from "@/components/ui/button";
import {
  Zap,
  BarChart3,
  ArrowRight,
  Target,
  ChevronDown,
  ChevronUp,
  Check,
  X,
  Shield,
  TrendingUp,
  Lock,
  Cpu,
  Menu,
  Moon,
  Sun,
  MessageSquare,
} from "lucide-react";

import { HomeEquityCurve } from "@/components/HomeEquityCurve";
import { ContactForm } from "@/components/ContactForm";
import {
  trackCTAClick,
  initTimeTracking,
  trackScrollDepth,
} from "@/lib/analytics";
import { getLoginUrl, getSignupUrl } from "@/const";
import { Link } from "wouter";
import { trpc } from "@/lib/trpc";
import { useState, useEffect } from "react";
import { useTheme } from "@/contexts/ThemeContext";

// FAQ data
const faqs = [
  {
    question: "What exactly do I get with an STS subscription?",
    answer:
      "A dashboard that shows you how our futures trading strategies have performed over 14+ years. You get the historical data, real-time trade signals, and risk metrics all in one place.",
  },
  {
    question: "Which markets and timeframes do the signals cover?",
    answer:
      "STS provides signals for NQ (Nasdaq-100) futures contracts. Signals are generated on an intraday basis — typically targeting moves that play out within the same trading day (minutes to hours). We focus on liquid, high-volume futures to ensure reliable real-time analysis.",
  },
  {
    question: "How are signals delivered? Do I need any special software?",
    answer:
      "All signals are delivered on our web-based dashboard in real time. There's no need for Telegram, Discord, or installing software. Just log into the STS dashboard from any web browser (desktop or mobile) and you'll see the latest signals streaming live. You can enable sound or email notifications within the dashboard if desired.",
  },
  {
    question: "What is the strategy or algorithm behind these signals?",
    answer:
      "Signals are generated by a proprietary algorithm developed by our quant (a seasoned futures trader). It combines technical analysis and AI-driven pattern recognition, honed on years of historical data. In simpler terms, it's constantly analyzing market momentum, order flow, and price patterns to identify high-probability trade setups.",
  },
  {
    question: "Is STS suitable for beginners?",
    answer:
      "Yes – you don't need trading experience to use STS effectively. Signals are straightforward (e.g., 'Buy NQ now, target X, stop Y'), and we provide a quick start guide to help with basics like order placement. Many of our users are new traders who use STS to learn what a good trade setup looks like.",
  },
  {
    question: "Do you offer support if I have questions or issues?",
    answer:
      "Absolutely. We offer support via email and in-dashboard chat. If you ever have a question about a signal or need help with your account, our support team is quick to respond (typically within a few hours on trading days). Plus, our dashboard includes helpful tooltips and an FAQ.",
  },
  {
    question: "Can I cancel if I'm not satisfied?",
    answer:
      "Yes, you can cancel anytime from your account settings. Your access will continue until the end of your current billing period.",
  },
];

// Comparison data
const comparisonFeatures = [
  {
    feature: "Backtested strategies (14+ years)",
    sts: true,
    discretionary: false,
    diy: "Months of work",
  },
  {
    feature: "Real-time TradingView signals",
    sts: true,
    discretionary: false,
    diy: "Build yourself",
  },
  {
    feature: "Kelly criterion position sizing",
    sts: true,
    discretionary: false,
    diy: "Build yourself",
  },
  {
    feature: "Risk-adjusted metrics (Sharpe, Sortino)",
    sts: true,
    discretionary: false,
    diy: "Build yourself",
  },
  {
    feature: "Portfolio correlation analysis",
    sts: true,
    discretionary: false,
    diy: "Build yourself",
  },
  {
    feature: "Personal dashboard & portfolio builder",
    sts: true,
    discretionary: false,
    diy: "Build yourself",
  },
  {
    feature: "Emotion-free execution",
    sts: true,
    discretionary: false,
    diy: true,
  },
  {
    feature: "24/7 market monitoring",
    sts: true,
    discretionary: false,
    diy: true,
  },
  {
    feature: "Time investment",
    sts: "Minutes/day",
    discretionary: "Hours/day",
    diy: "Months to build",
  },
];

// Features list
const features = [
  {
    icon: Zap,
    title: "Real-Time Signals",
    description:
      "When a strategy triggers, you'll see it on your dashboard immediately.",
  },
  {
    icon: Cpu,
    title: "Trend-Following Strategy",
    description:
      "NQ futures strategy backtested over 15 years of historical data with consistent performance.",
  },
  {
    icon: Target,
    title: "Entry & Exit Levels",
    description:
      "Each signal shows the entry price, stop loss, and profit target.",
  },
  {
    icon: TrendingUp,
    title: "Futures Market Focused",
    description:
      "Strategies built for the most liquid futures markets in the world, focused on NQ (Nasdaq-100).",
  },
  {
    icon: BarChart3,
    title: "Full Trade History",
    description:
      "See every trade from the past 15 years with complete performance data.",
  },
  {
    icon: Shield,
    title: "Web Dashboard",
    description:
      "Everything in one place. No Discord channels or Telegram groups.",
  },
];

export default function LandingPage() {
  // Check if user is authenticated by checking for auth token
  const isAuthenticated = !!localStorage.getItem("auth_token");
  const [openFaq, setOpenFaq] = useState<number | null>(null);
  const [mobileMenuOpen, setMobileMenuOpen] = useState(false);
  const { theme, toggleTheme } = useTheme();

  // Set page title for SEO
  useEffect(() => {
    document.title =
      "STS Futures | NQ Futures Trading Signals & Performance Dashboard";
    initTimeTracking();

    const handleScroll = () => {
      const scrollPercent = Math.round(
        (window.scrollY /
          (document.documentElement.scrollHeight - window.innerHeight)) *
          100
      );
      if (scrollPercent >= 25 && scrollPercent < 50) trackScrollDepth(25);
      else if (scrollPercent >= 50 && scrollPercent < 75) trackScrollDepth(50);
      else if (scrollPercent >= 75 && scrollPercent < 90) trackScrollDepth(75);
      else if (scrollPercent >= 90) trackScrollDepth(100);
    };

    window.addEventListener("scroll", handleScroll, { passive: true });
    return () => window.removeEventListener("scroll", handleScroll);
  }, []);

  // Platform stats and strategies queries
  trpc.platform.stats.useQuery();
  trpc.subscription.availableStrategies.useQuery(undefined, {
    enabled: isAuthenticated,
  });

  const handleCTAClick = (location: "hero" | "pricing" | "nav" | "footer") => {
    trackCTAClick(location);
    if (!isAuthenticated) {
      window.location.href = getLoginUrl();
    } else {
      window.location.href = "/checkout";
    }
  };

  return (
    <div className="min-h-screen bg-background">
      {/* Navigation Bar */}
      <nav className="fixed top-0 left-0 right-0 z-50 bg-background/80 backdrop-blur-lg border-b border-border">
        <div className="container flex items-center justify-between h-16 px-4">
          <Link href="/">
            <div className="flex items-center gap-3 cursor-pointer">
              <img
                src="https://files.manuscdn.com/user_upload_by_module/session_file/110198424/sLgasntqXJoSfWmA.png"
                alt="STS"
                className="w-9 h-9"
              />
              <span className="text-xl font-bold text-foreground tracking-tight">
                STS
              </span>
              <span className="hidden sm:inline text-[10px] text-emerald-400/80 font-medium tracking-wider uppercase">
                Futures
              </span>
            </div>
          </Link>

          {/* Desktop Navigation */}
          <div className="hidden md:flex items-center gap-4">
            <Button
              variant="outline"
              size="icon"
              onClick={toggleTheme}
              className="border-emerald-500/30 hover:bg-emerald-500/10 hover:border-emerald-500"
              aria-label="Toggle theme"
            >
              {theme === "dark" ? (
                <Sun className="h-5 w-5 text-emerald-400" />
              ) : (
                <Moon className="h-5 w-5 text-emerald-600" />
              )}
            </Button>
            <ContactForm
              trigger={
                <Button
                  variant="ghost"
                  className="text-muted-foreground hover:text-foreground hover:bg-emerald-500/10"
                >
                  <MessageSquare className="h-4 w-4 mr-2" />
                  Contact
                </Button>
              }
            />
            {isAuthenticated ? (
              <Button
                onClick={() => (window.location.href = "/overview")}
                className="bg-emerald-500 hover:bg-emerald-600 text-foreground"
              >
                Dashboard
              </Button>
            ) : (
              <>
                <Button
                  onClick={() => (window.location.href = getLoginUrl())}
                  variant="outline"
                  className="border-emerald-500/50 text-emerald-400 hover:bg-emerald-500/10"
                >
                  Sign In
                </Button>
                <Button
                  onClick={() => (window.location.href = getSignupUrl())}
                  className="bg-emerald-500 hover:bg-emerald-600 text-foreground"
                >
                  Get Started
                </Button>
              </>
            )}
          </div>

          {/* Mobile Hamburger Button */}
          <button
            onClick={() => setMobileMenuOpen(!mobileMenuOpen)}
            className="md:hidden p-2 text-muted-foreground hover:text-foreground transition-colors"
            aria-label="Toggle menu"
          >
            {mobileMenuOpen ? (
              <X className="h-6 w-6" />
            ) : (
              <Menu className="h-6 w-6" />
            )}
          </button>
        </div>

        {/* Mobile Menu Dropdown */}
        {mobileMenuOpen && (
          <div className="md:hidden bg-background/95 backdrop-blur-lg border-b border-border">
            <div className="container px-4 py-4 flex flex-col gap-3">
              <Button
                variant="outline"
                onClick={toggleTheme}
                className="w-full border-emerald-500/30 hover:bg-emerald-500/10"
              >
                {theme === "dark" ? (
                  <>
                    <Sun className="h-5 w-5 text-emerald-400 mr-2" /> Light Mode
                  </>
                ) : (
                  <>
                    <Moon className="h-5 w-5 text-emerald-600 mr-2" /> Dark Mode
                  </>
                )}
              </Button>
              <ContactForm
                trigger={
                  <Button
                    variant="outline"
                    className="w-full border-emerald-500/30 text-muted-foreground hover:text-foreground hover:bg-emerald-500/10"
                  >
                    <MessageSquare className="h-4 w-4 mr-2" />
                    Contact Us
                  </Button>
                }
              />
              {isAuthenticated ? (
                <Button
                  onClick={() => {
                    setMobileMenuOpen(false);
                    window.location.href = "/overview";
                  }}
                  className="w-full bg-emerald-500 hover:bg-emerald-600 text-foreground"
                >
                  Dashboard
                </Button>
              ) : (
                <>
                  <Button
                    onClick={() => {
                      setMobileMenuOpen(false);
                      window.location.href = getLoginUrl();
                    }}
                    variant="outline"
                    className="w-full border-emerald-500/50 text-emerald-400 hover:bg-emerald-500/10"
                  >
                    Sign In
                  </Button>
                  <Button
                    onClick={() => {
                      setMobileMenuOpen(false);
                      window.location.href = getSignupUrl();
                    }}
                    className="w-full bg-emerald-500 hover:bg-emerald-600 text-foreground"
                  >
                    Get Started
                  </Button>
                </>
              )}
            </div>
          </div>
        )}
      </nav>

      {/* HERO SECTION */}
      <header className="relative pt-32 pb-20 px-4 md:pt-40 md:pb-32 overflow-hidden">
        {/* Background gradient */}
        <div className="absolute inset-0 -z-10">
          <div className="absolute top-0 left-1/4 w-96 h-96 bg-emerald-500/10 rounded-full blur-3xl" />
          <div className="absolute bottom-0 right-1/4 w-96 h-96 bg-blue-500/10 rounded-full blur-3xl" />
        </div>

        <div className="container max-w-4xl mx-auto text-center">
          {/* Tagline */}
          <div className="mb-6 inline-block px-4 py-2 bg-emerald-500/10 border border-emerald-500/30 rounded-full">
            <span className="text-sm font-medium text-emerald-400">
              Real-Time Trading Signals
            </span>
          </div>

          {/* Main Headline */}
          <h1 className="text-3xl sm:text-4xl md:text-5xl lg:text-6xl font-bold text-foreground mb-6 leading-tight">
            Systematic Trading Algo
            <br />
            15 Years Of Data
            <br />
            <span className="text-primary">Real Time Alerts</span>
          </h1>

          {/* Subheadline */}
          <p className="text-base sm:text-lg md:text-xl text-foreground/80 mb-8 max-w-2xl mx-auto leading-relaxed">
            You get a dashboard showing our futures strategies' complete track
            record. Every single trade. Every win and loss. All the stats. No
            surprises.
          </p>

          {/* Primary CTA */}
          <div className="flex flex-col sm:flex-row gap-4 justify-center mb-8">
            {isAuthenticated ? (
              <Button
                onClick={() => (window.location.href = "/overview")}
                size="lg"
                className="bg-emerald-500 hover:bg-emerald-600 text-foreground px-6 sm:px-8 py-5 sm:py-6 text-base sm:text-lg font-semibold"
              >
                Go to Dashboard{" "}
              </Button>
            ) : (
              <>
                <Button
                  onClick={() => (window.location.href = getSignupUrl())}
                  size="lg"
                  className="bg-emerald-500 hover:bg-emerald-600 text-foreground px-6 sm:px-8 py-5 sm:py-6 text-base sm:text-lg font-semibold"
                >
                  View Pricing
                </Button>
                <Button
                  onClick={() => (window.location.href = getLoginUrl())}
                  size="lg"
                  variant="outline"
                  className="border-emerald-500/50 text-emerald-400 hover:bg-emerald-500/10 px-6 sm:px-8 py-5 sm:py-6 text-base sm:text-lg font-semibold"
                >
                  Sign In
                </Button>
              </>
            )}
          </div>

          {/* Trust note */}
          <p className="text-xs sm:text-sm text-muted-foreground px-2">
            ✓ Notification delivery: STS Dashboard web-based · No Discord or
            Telegram required
          </p>
        </div>

        {/* Hero Visual - Equity Chart */}
        <div className="mt-12 sm:mt-16 max-w-5xl mx-auto px-2 sm:px-0">
          <div className="bg-gradient-to-b from-card to-transparent rounded-lg border border-border p-3 sm:p-6 backdrop-blur">
            <HomeEquityCurve />
          </div>
        </div>
      </header>

      {/* SOCIAL PROOF & TRUST BUILDERS SECTION */}
      <section className="py-16 px-4 bg-gradient-to-b from-transparent to-muted/30 border-y border-border">
        <div className="container max-w-4xl mx-auto">
          {/* Proof bar */}
          <div className="text-center mb-12">
            <p className="text-sm text-emerald-400 font-medium">
              ✓ 14+ years of backtested data · Real-time signals · No hidden
              metrics
            </p>
          </div>

          {/* Trust badges */}
          <div className="mt-12 flex flex-wrap justify-center gap-6 items-center">
            <div className="flex items-center gap-2 text-muted-foreground">
              <Lock className="w-4 h-4 text-emerald-400" />
              <span className="text-sm">Secure & Private</span>
            </div>
            <div className="flex items-center gap-2 text-muted-foreground">
              <Shield className="w-4 h-4 text-emerald-400" />
              <span className="text-sm">Quant-Driven</span>
            </div>
            <div className="flex items-center gap-2 text-muted-foreground">
              <BarChart3 className="w-4 h-4 text-emerald-400" />
              <span className="text-sm">Real-Time Data</span>
            </div>
          </div>
        </div>
      </section>

      {/* FEATURES & BENEFITS SECTION */}
      <section id="features" className="py-20 px-4">
        <div className="container max-w-5xl mx-auto">
          {/* Section header */}
          <div className="text-center mb-16">
            <h2 className="text-2xl sm:text-3xl md:text-4xl font-bold text-foreground mb-4">
              How It Works
            </h2>
            <p className="text-lg text-muted-foreground">
              From sign-up to your first trade in under 5 minutes
            </p>
          </div>

          {/* 3-step process */}
          <div className="grid md:grid-cols-3 gap-8 mb-16">
            {[
              {
                step: 1,
                title: "Sign Up in Seconds",
                description:
                  "No downloads. No complicated setup. Just log in and your entire trading command center is ready.",
              },
              {
                step: 2,
                title: "See the Proof",
                description:
                  "15 years of real trades. Every win. Every loss. Full transparency so you can trade with confidence, not hope.",
              },
              {
                step: 3,
                title: "Trade with Clarity",
                description:
                  "Get real-time signals with exact entry, stop, and target levels. No guesswork. No second-guessing. Just execute.",
              },
            ].map((item, idx) => (
              <div key={idx} className="relative">
                <div className="bg-card rounded-lg p-8 border border-border h-full">
                  <div className="flex items-center gap-4 mb-4">
                    <div className="w-10 h-10 rounded-full bg-emerald-500/20 border border-emerald-500/50 flex items-center justify-center">
                      <span className="font-bold text-emerald-400">
                        {item.step}
                      </span>
                    </div>
                  </div>
                  <h3 className="text-xl font-semibold text-foreground mb-2">
                    {item.title}
                  </h3>
                  <p className="text-muted-foreground">{item.description}</p>
                </div>
                {idx < 2 && (
                  <div className="hidden md:flex absolute top-1/2 -right-4 transform -translate-y-1/2">
                    <ArrowRight className="w-6 h-6 text-emerald-500/50" />
                  </div>
                )}
              </div>
            ))}
          </div>

          {/* Key features */}
          <div className="mt-20">
            <h3 className="text-2xl font-bold text-foreground mb-12 text-center">
              Key Features
            </h3>
            <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-6">
              {features.map((feature, idx) => {
                const Icon = feature.icon;
                return (
                  <div
                    key={idx}
                    className="bg-card rounded-lg p-6 border border-border"
                  >
                    <Icon className="w-8 h-8 text-emerald-400 mb-4" />
                    <h4 className="font-semibold text-foreground mb-2">
                      {feature.title}
                    </h4>
                    <p className="text-sm text-muted-foreground">
                      {feature.description}
                    </p>
                  </div>
                );
              })}
            </div>
          </div>
        </div>
      </section>

      {/* DASHBOARD PREVIEW / FEATURE SHOWCASE SECTION */}
      <section
        id="preview"
        className="py-20 px-4 bg-muted/50 border-y border-border"
      >
        <div className="container max-w-6xl mx-auto">
          <div className="text-center mb-16">
            <span className="text-xs font-semibold text-emerald-400 tracking-wider uppercase">
              Inside The Dashboard
            </span>
            <h2 className="text-2xl sm:text-3xl md:text-4xl font-bold text-foreground mt-2 mb-4">
              See Exactly What You Get
            </h2>
            <p className="text-lg text-muted-foreground max-w-2xl mx-auto">
              No guessing. Here's what your dashboard looks like from day one.
            </p>
          </div>

          {/* Feature 1: Metrics & Settings */}
          <div className="mb-20">
            <div className="grid lg:grid-cols-5 gap-8 items-center">
              <div className="lg:col-span-2 order-2 lg:order-1">
                <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-emerald-500/10 text-emerald-500 text-xs font-semibold mb-4">
                  <Target className="w-3.5 h-3.5" />
                  Portfolio Settings
                </div>
                <h3 className="text-xl sm:text-2xl font-bold text-foreground mb-3">
                  Customize Your View
                </h3>
                <p className="text-muted-foreground leading-relaxed">
                  Pick your time range, contract size, and account value. The
                  dashboard recalculates everything instantly so you see
                  performance numbers that match your trading setup.
                </p>
                <div className="mt-4 space-y-2">
                  <div className="flex items-center gap-2 text-sm text-muted-foreground">
                    <Check className="w-4 h-4 text-emerald-400" />
                    Sortino, Sharpe, Calmar ratios at a glance
                  </div>
                  <div className="flex items-center gap-2 text-sm text-muted-foreground">
                    <Check className="w-4 h-4 text-emerald-400" />
                    Win rate and total return updated in real time
                  </div>
                  <div className="flex items-center gap-2 text-sm text-muted-foreground">
                    <Check className="w-4 h-4 text-emerald-400" />
                    Micro or Mini contract sizing
                  </div>
                </div>
              </div>
              <div className="lg:col-span-3 order-1 lg:order-2">
                <div className="rounded-xl overflow-hidden shadow-2xl shadow-emerald-500/5 border border-border">
                  <img
                    src="https://files.manuscdn.com/user_upload_by_module/session_file/110198424/gRwVdZUTBirkElFV.png"
                    alt="Dashboard metrics and portfolio settings showing Sortino, Sharpe, Calmar ratios and win rate"
                    className="w-full h-auto"
                    loading="lazy"
                  />
                </div>
              </div>
            </div>
          </div>

          {/* Feature 2: Equity Curve */}
          <div className="mb-20">
            <div className="grid lg:grid-cols-5 gap-8 items-center">
              <div className="lg:col-span-3">
                <div className="rounded-xl overflow-hidden shadow-2xl shadow-emerald-500/5 border border-border">
                  <img
                    src="https://files.manuscdn.com/user_upload_by_module/session_file/110198424/fktdaEKbPpDWHAhw.png"
                    alt="Live equity curve chart showing portfolio growth over time with time range selector"
                    className="w-full h-auto"
                    loading="lazy"
                  />
                </div>
              </div>
              <div className="lg:col-span-2">
                <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-emerald-500/10 text-emerald-500 text-xs font-semibold mb-4">
                  <TrendingUp className="w-3.5 h-3.5" />
                  Equity Curve
                </div>
                <h3 className="text-xl sm:text-2xl font-bold text-foreground mb-3">
                  Watch Your Edge Grow
                </h3>
                <p className="text-muted-foreground leading-relaxed">
                  A live equity curve that tracks every dollar gained or lost.
                  Zoom into 6 months or zoom out to see the full 15-year track
                  record. The green dashed line is your starting capital so you
                  always know where you stand.
                </p>
                <div className="mt-4 space-y-2">
                  <div className="flex items-center gap-2 text-sm text-muted-foreground">
                    <Check className="w-4 h-4 text-emerald-400" />
                    6M, YTD, 1Y, 5Y, 10Y, and ALL time ranges
                  </div>
                  <div className="flex items-center gap-2 text-sm text-muted-foreground">
                    <Check className="w-4 h-4 text-emerald-400" />
                    Starting capital reference line
                  </div>
                  <div className="flex items-center gap-2 text-sm text-muted-foreground">
                    <Check className="w-4 h-4 text-emerald-400" />
                    Interactive tooltips with exact values
                  </div>
                </div>
              </div>
            </div>
          </div>

          {/* Feature 3: Trade Stats */}
          <div className="mb-20">
            <div className="grid lg:grid-cols-5 gap-8 items-center">
              <div className="lg:col-span-2 order-2 lg:order-1">
                <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-emerald-500/10 text-emerald-500 text-xs font-semibold mb-4">
                  <BarChart3 className="w-3.5 h-3.5" />
                  Live Trades & Distribution
                </div>
                <h3 className="text-xl sm:text-2xl font-bold text-foreground mb-3">
                  Live Positions & Returns
                </h3>
                <p className="text-muted-foreground leading-relaxed">
                  See every open position in real time with entry prices and
                  contract counts. Below that, a daily returns distribution
                  histogram shows you exactly how your P&L is spread across 363
                  trading days with tail analysis stats.
                </p>
                <div className="mt-4 space-y-2">
                  <div className="flex items-center gap-2 text-sm text-muted-foreground">
                    <Check className="w-4 h-4 text-emerald-400" />
                    Live current positions with entry prices
                  </div>
                  <div className="flex items-center gap-2 text-sm text-muted-foreground">
                    <Check className="w-4 h-4 text-emerald-400" />
                    Daily returns histogram with skewness & kurtosis
                  </div>
                  <div className="flex items-center gap-2 text-sm text-muted-foreground">
                    <Check className="w-4 h-4 text-emerald-400" />
                    Recent trade alerts and notifications
                  </div>
                </div>
              </div>
              <div className="lg:col-span-3 order-1 lg:order-2">
                <div className="rounded-xl overflow-hidden shadow-2xl shadow-emerald-500/5 border border-border">
                  <img
                    src="https://files.manuscdn.com/user_upload_by_module/session_file/110198424/BScOYWPFVPdHcQSO.png"
                    alt="Live current positions, recent alerts, and daily returns distribution histogram with tail analysis"
                    className="w-full h-auto"
                    loading="lazy"
                  />
                </div>
              </div>
            </div>
          </div>

          {/* Feature 4: Calendar Heatmap */}
          <div className="mb-8">
            <div className="grid lg:grid-cols-5 gap-8 items-center">
              <div className="lg:col-span-3">
                <div className="rounded-xl overflow-hidden shadow-2xl shadow-emerald-500/5 border border-border">
                  <img
                    src="https://files.manuscdn.com/user_upload_by_module/session_file/110198424/SWPtfhpONNOVecqF.png"
                    alt="Day-of-week performance cards showing average P&L and win rates, plus rolling Sharpe ratio chart"
                    className="w-full h-auto"
                    loading="lazy"
                  />
                </div>
              </div>
              <div className="lg:col-span-2">
                <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-emerald-500/10 text-emerald-500 text-xs font-semibold mb-4">
                  <Zap className="w-3.5 h-3.5" />
                  Performance Breakdown
                </div>
                <h3 className="text-xl sm:text-2xl font-bold text-foreground mb-3">
                  Know Your Best Days
                </h3>
                <p className="text-muted-foreground leading-relaxed">
                  Day-of-week cards show you which days make the most money.
                  Fridays average $1,226 per trade. Rolling Sharpe and Sortino
                  charts track how your edge changes over time so you can spot
                  when a strategy is heating up or cooling down.
                </p>
                <div className="mt-4 space-y-2">
                  <div className="flex items-center gap-2 text-sm text-muted-foreground">
                    <Check className="w-4 h-4 text-emerald-400" />
                    Day-of-week P&L with win rates and avg win/loss
                  </div>
                  <div className="flex items-center gap-2 text-sm text-muted-foreground">
                    <Check className="w-4 h-4 text-emerald-400" />
                    Rolling Sharpe Ratio chart (Current: 2.24)
                  </div>
                  <div className="flex items-center gap-2 text-sm text-muted-foreground">
                    <Check className="w-4 h-4 text-emerald-400" />
                    Rolling Sortino Ratio for downside risk tracking
                  </div>
                </div>
              </div>
            </div>
          </div>

          {/* CTA after previews */}
          <div className="text-center mt-16">
            <p className="text-muted-foreground mb-6">
              This is just a preview. The full dashboard has even more.
            </p>
            <Button
              onClick={() => handleCTAClick("pricing")}
              size="lg"
              className="bg-emerald-500 hover:bg-emerald-600 text-white px-8 py-6 text-lg font-semibold"
            >
              {isAuthenticated ? "Go to Dashboard" : "Get Full Access"}
              <ArrowRight className="w-5 h-5 ml-2" />
            </Button>
          </div>
        </div>
      </section>

      {/* COMPARISON SECTION */}
      <section id="compare" className="py-20 px-4 border-y border-border">
        <div className="container max-w-5xl mx-auto">
          <div className="text-center mb-16">
            <span className="text-xs font-semibold text-emerald-400 tracking-wider uppercase">
              Compare
            </span>
            <h2 className="text-2xl sm:text-3xl md:text-4xl font-bold text-foreground mt-2 mb-4">
              STS vs. the alternatives.
            </h2>
            <p className="text-lg text-muted-foreground">
              See how we stack up.
            </p>
          </div>

          {/* Comparison table */}
          <div className="overflow-x-auto">
            <table className="w-full">
              <thead>
                <tr className="border-b border-border">
                  <th className="text-left py-4 px-4 text-muted-foreground font-semibold">
                    Feature
                  </th>
                  <th className="text-center py-4 px-4 text-emerald-400 font-semibold">
                    STS
                  </th>
                  <th className="text-center py-4 px-4 text-muted-foreground font-semibold">
                    Discretionary
                  </th>
                  <th className="text-center py-4 px-4 text-muted-foreground font-semibold">
                    DIY
                  </th>
                </tr>
              </thead>
              <tbody>
                {comparisonFeatures.map((item, idx) => (
                  <tr key={idx} className="border-b border-border">
                    <td className="py-4 px-4 text-foreground/80">
                      {item.feature}
                    </td>
                    <td className="py-4 px-4 text-center">
                      {item.sts === true ? (
                        <Check className="w-5 h-5 text-emerald-400 mx-auto" />
                      ) : (
                        <span className="text-muted-foreground">
                          {item.sts}
                        </span>
                      )}
                    </td>
                    <td className="py-4 px-4 text-center">
                      {item.discretionary === true ? (
                        <Check className="w-5 h-5 text-emerald-400 mx-auto" />
                      ) : (
                        <X className="w-5 h-5 text-red-400 mx-auto" />
                      )}
                    </td>
                    <td className="py-4 px-4 text-center">
                      {item.diy === true ? (
                        <Check className="w-5 h-5 text-emerald-400 mx-auto" />
                      ) : typeof item.diy === "string" ? (
                        <span className="text-muted-foreground text-sm">
                          {item.diy}
                        </span>
                      ) : (
                        <X className="w-5 h-5 text-red-400 mx-auto" />
                      )}
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>
      </section>

      {/* PRICING SECTION */}
      <section id="pricing" className="py-20 px-4">
        <div className="container max-w-4xl mx-auto">
          <div className="text-center mb-16">
            <h2 className="text-2xl sm:text-3xl md:text-4xl font-bold text-foreground mb-4">
              Plans & Pricing
            </h2>
            <p className="text-lg text-muted-foreground">
              Simple, transparent pricing. No hidden fees.
            </p>
          </div>

          {/* Pricing card */}
          <div className="bg-gradient-to-br from-card to-muted rounded-lg border border-emerald-500/30 p-6 sm:p-8 max-w-md mx-auto">
            <div className="text-center mb-8">
              <h3 className="text-2xl font-bold text-foreground mb-2">
                Professional Plan
              </h3>
              <div className="flex items-baseline justify-center gap-1">
                <span className="text-4xl font-bold text-foreground">$50</span>
                <span className="text-muted-foreground">/month</span>
              </div>
              <p className="text-sm text-emerald-400 mt-2">Billed monthly</p>
            </div>

            {/* Features included */}
            <div className="space-y-4 mb-8">
              <div className="flex items-start gap-3">
                <Check className="w-5 h-5 text-emerald-400 flex-shrink-0 mt-0.5" />
                <span className="text-foreground/80">
                  Real-time futures trading signals
                </span>
              </div>
              <div className="flex items-start gap-3">
                <Check className="w-5 h-5 text-emerald-400 flex-shrink-0 mt-0.5" />
                <span className="text-foreground/80">
                  Full access to STS web dashboard
                </span>
              </div>
              <div className="flex items-start gap-3">
                <Check className="w-5 h-5 text-emerald-400 flex-shrink-0 mt-0.5" />
                <span className="text-foreground/80">
                  All updates and new strategies
                </span>
              </div>
              <div className="flex items-start gap-3">
                <Check className="w-5 h-5 text-emerald-400 flex-shrink-0 mt-0.5" />
                <span className="text-foreground/80">Email support</span>
              </div>
              <div className="flex items-start gap-3">
                <Check className="w-5 h-5 text-emerald-400 flex-shrink-0 mt-0.5" />
                <span className="text-foreground/80">
                  Onboarding guide & resources
                </span>
              </div>
            </div>

            {/* CTA Button */}
            <Button
              onClick={() => handleCTAClick("pricing")}
              size="lg"
              className="w-full bg-emerald-500 hover:bg-emerald-600 text-foreground py-6 text-lg font-semibold mb-6"
            >
              {isAuthenticated ? "Go to Dashboard" : "Subscribe Now"}
            </Button>

            {/* Guarantees */}
            <div className="space-y-3 text-center text-sm text-muted-foreground border-t border-border pt-6">
              <p>✓ Cancel anytime, no questions asked</p>
              <p>✓ Secure 256-bit encrypted checkout</p>
              <p>✓ Instant access to all features</p>
            </div>
          </div>

          {/* Payment info */}
          <div className="text-center mt-8 text-sm text-muted-foreground">
            <p>We accept all major credit cards · Powered by Stripe</p>
          </div>
        </div>
      </section>

      {/* FAQ SECTION */}
      <section
        id="faq"
        className="py-20 px-4 bg-muted/50 border-y border-border"
      >
        <div className="container max-w-3xl mx-auto">
          <div className="text-center mb-16">
            <h2 className="text-2xl sm:text-3xl md:text-4xl font-bold text-foreground mb-4">
              Frequently Asked Questions
            </h2>
            <p className="text-lg text-muted-foreground">
              Everything you need to know about STS
            </p>
          </div>

          {/* FAQ Accordion */}
          <div className="space-y-4">
            {faqs.map((faq, idx) => (
              <div
                key={idx}
                className="bg-card rounded-lg border border-border overflow-hidden"
              >
                <button
                  onClick={() => setOpenFaq(openFaq === idx ? null : idx)}
                  className="w-full px-4 sm:px-6 py-4 flex items-center justify-between hover:bg-accent transition-colors text-left"
                >
                  <span className="text-left font-semibold text-foreground">
                    {faq.question}
                  </span>
                  {openFaq === idx ? (
                    <ChevronUp className="w-5 h-5 text-emerald-400 flex-shrink-0" />
                  ) : (
                    <ChevronDown className="w-5 h-5 text-muted-foreground flex-shrink-0" />
                  )}
                </button>
                {openFaq === idx && (
                  <div className="px-6 py-4 border-t border-border bg-muted">
                    <p className="text-foreground/80 leading-relaxed">
                      {faq.answer}
                    </p>
                  </div>
                )}
              </div>
            ))}
          </div>

          {/* Contact CTA */}
          <div className="text-center mt-12">
            <p className="text-muted-foreground mb-4">Still have questions?</p>
            <ContactForm
              trigger={
                <Button
                  variant="outline"
                  className="border-emerald-500/50 text-emerald-400 hover:bg-emerald-500/10"
                >
                  <MessageSquare className="h-4 w-4 mr-2" />
                  Contact Us
                </Button>
              }
            />
          </div>
        </div>
      </section>

      {/* FINAL CTA SECTION */}
      <section className="py-20 px-4 bg-gradient-to-b from-transparent to-card">
        <div className="container max-w-3xl mx-auto text-center">
          <h2 className="text-2xl sm:text-3xl md:text-4xl font-bold text-foreground mb-6">
            Ready to trade smarter?
          </h2>
          <p className="text-lg text-muted-foreground mb-8">
            Join traders who've replaced guesswork with proven, algorithmic
            signals.
          </p>
          <Button
            onClick={() => handleCTAClick("footer")}
            size="lg"
            className="bg-emerald-500 hover:bg-emerald-600 text-foreground px-6 sm:px-8 py-5 sm:py-6 text-base sm:text-lg font-semibold"
          >
            {isAuthenticated ? "Go to Checkout" : "Subscribe Now"}
            <ArrowRight className="ml-2 w-5 h-5" />
          </Button>
        </div>
      </section>

      {/* FOOTER */}
      <footer className="border-t border-border bg-muted py-12 px-4">
        <div className="container max-w-5xl mx-auto">
          <div className="grid md:grid-cols-4 gap-8 mb-12">
            <div>
              <div className="flex items-center gap-2 mb-4">
                <img
                  src="https://files.manuscdn.com/user_upload_by_module/session_file/110198424/sLgasntqXJoSfWmA.png"
                  alt="STS"
                  className="w-6 h-6"
                />
                <span className="font-bold text-foreground">STS Futures</span>
              </div>
              <p className="text-sm text-muted-foreground">
                Real-time futures trading signals powered by algorithmic
                analysis.
              </p>
            </div>
            <div>
              <h4 className="font-semibold text-foreground mb-4">Product</h4>
              <ul className="space-y-2 text-sm text-muted-foreground">
                <li>
                  <a
                    href="#features"
                    className="hover:text-foreground transition-colors"
                  >
                    Features
                  </a>
                </li>
                <li>
                  <a
                    href="#pricing"
                    className="hover:text-foreground transition-colors"
                  >
                    Pricing
                  </a>
                </li>
                <li>
                  <a
                    href="#faq"
                    className="hover:text-foreground transition-colors"
                  >
                    FAQ
                  </a>
                </li>
              </ul>
            </div>
            <div>
              <h4 className="font-semibold text-foreground mb-4">Legal</h4>
              <ul className="space-y-2 text-sm text-muted-foreground">
                <li>
                  <a
                    href="/terms"
                    className="hover:text-foreground transition-colors"
                  >
                    Terms of Service
                  </a>
                </li>
                <li>
                  <a
                    href="/privacy"
                    className="hover:text-foreground transition-colors"
                  >
                    Privacy Policy
                  </a>
                </li>
                <li>
                  <a
                    href="/refund-policy"
                    className="hover:text-foreground transition-colors"
                  >
                    Cancellation Policy
                  </a>
                </li>
                <li>
                  <a
                    href="/disclaimer"
                    className="hover:text-foreground transition-colors"
                  >
                    Disclaimer
                  </a>
                </li>
                <li>
                  <a
                    href="/risk-disclosure"
                    className="hover:text-foreground transition-colors"
                  >
                    Risk Disclosure
                  </a>
                </li>
              </ul>
            </div>
            <div>
              <h4 className="font-semibold text-foreground mb-4">Support</h4>
              <ul className="space-y-2 text-sm text-muted-foreground">
                <li>
                  <a
                    href="#faq"
                    className="hover:text-foreground transition-colors"
                  >
                    Help Center
                  </a>
                </li>
                <li>
                  <ContactForm
                    trigger={
                      <button className="hover:text-foreground transition-colors text-sm text-muted-foreground text-left">
                        Email Support
                      </button>
                    }
                    defaultCategory="support"
                  />
                </li>
              </ul>
            </div>
          </div>

          <div className="border-t border-border pt-8 text-center text-sm text-muted-foreground">
            <p>© 2026 STS Futures. All rights reserved.</p>
            <p className="mt-2 text-xs">
              Past performance is not indicative of future results. Trading
              involves substantial risk of loss.
            </p>
          </div>
        </div>
      </footer>
    </div>
  );
}
