/**
 * Auto-generate sitemap.xml from the manifest of static routes + blog posts.
 *
 * Run it whenever a blog post is added/updated:
 *   node --import tsx scripts/generate-sitemap.mts
 *
 * Or wire into CI to run on every commit that touches
 * client/public/blog/manifest.json.
 *
 * Why: keeping sitemap.xml in sync with blog manifest.json by hand is
 * error-prone. This script is the canonical source and should replace
 * the hand-maintained sitemap.xml on any future content change.
 */
import fs from "node:fs";
import path from "node:path";

const SITE = "https://stsdashboard.com";
const ROOT = path.resolve(
  path.dirname(new URL(import.meta.url).pathname.replace(/^\/([A-Za-z]:)/, "$1")),
  ".."
);
const MANIFEST_PATH = path.join(ROOT, "client", "public", "blog", "manifest.json");
const SITEMAP_PATH = path.join(ROOT, "client", "public", "sitemap.xml");

interface StaticRoute {
  path: string;
  priority: number;
  changefreq:
    | "always"
    | "hourly"
    | "daily"
    | "weekly"
    | "monthly"
    | "yearly"
    | "never";
  lastmod?: string;
  comment?: string;
}

const TODAY = new Date().toISOString().slice(0, 10);

// Curated list of public, indexable static routes. Add new public routes here.
// Admin / auth / legal-with-noindex routes should NOT be here.
const STATIC_ROUTES: StaticRoute[] = [
  { path: "/", priority: 1.0, changefreq: "weekly", lastmod: TODAY, comment: "Homepage / landing" },
  { path: "/pricing", priority: 0.9, changefreq: "monthly", lastmod: TODAY },
  { path: "/about", priority: 0.9, changefreq: "monthly", lastmod: TODAY, comment: "E-E-A-T authority" },
  { path: "/how-it-works", priority: 0.9, changefreq: "monthly", lastmod: TODAY, comment: "HowTo schema target" },
  { path: "/blog", priority: 0.9, changefreq: "weekly", lastmod: TODAY, comment: "Blog index, updates with every post" },
  { path: "/compare", priority: 0.7, changefreq: "monthly", lastmod: TODAY },
  { path: "/compare/signalstack", priority: 0.7, changefreq: "quarterly" as any, lastmod: TODAY },
  { path: "/compare/traderspost", priority: 0.7, changefreq: "quarterly" as any, lastmod: TODAY },
  { path: "/compare/discord-signal-services", priority: 0.7, changefreq: "quarterly" as any, lastmod: TODAY },
  { path: "/testimonials", priority: 0.6, changefreq: "monthly", lastmod: TODAY },
  { path: "/qa", priority: 0.8, changefreq: "monthly", lastmod: TODAY, comment: "FAQ" },
  { path: "/broker-setup", priority: 0.7, changefreq: "monthly", lastmod: TODAY },
  { path: "/terms", priority: 0.4, changefreq: "yearly", lastmod: TODAY },
  { path: "/privacy", priority: 0.4, changefreq: "yearly", lastmod: TODAY },
  { path: "/refund-policy", priority: 0.4, changefreq: "yearly", lastmod: TODAY },
  { path: "/disclaimer", priority: 0.4, changefreq: "yearly", lastmod: TODAY },
  { path: "/risk-disclosure", priority: 0.4, changefreq: "yearly", lastmod: TODAY },
];

interface BlogPost {
  slug: string;
  publishedAt: string;
  updatedAt?: string;
  category?: string;
}

function readBlogPosts(): BlogPost[] {
  if (!fs.existsSync(MANIFEST_PATH)) {
    console.warn(`[sitemap] no manifest at ${MANIFEST_PATH}`);
    return [];
  }
  const m = JSON.parse(fs.readFileSync(MANIFEST_PATH, "utf-8"));
  return (m.posts ?? []) as BlogPost[];
}

function urlEntry(
  loc: string,
  lastmod: string,
  changefreq: string,
  priority: number,
  comment?: string
): string {
  return `${comment ? `  <!-- ${comment} -->\n` : ""}  <url>
    <loc>${SITE}${loc}</loc>
    <lastmod>${lastmod}</lastmod>
    <changefreq>${changefreq}</changefreq>
    <priority>${priority.toFixed(1)}</priority>
  </url>`;
}

function build(): string {
  const staticEntries = STATIC_ROUTES.map(r =>
    urlEntry(r.path, r.lastmod || TODAY, r.changefreq, r.priority, r.comment)
  );
  const posts = readBlogPosts();
  const blogEntries = posts.map(p => {
    const lastmod = p.updatedAt || p.publishedAt;
    const isRecap = p.category === "weekly-recap";
    const priority = isRecap ? 0.7 : 0.8;
    const changefreq = isRecap ? "never" : "monthly";
    return urlEntry(
      `/blog/${p.slug}`,
      lastmod,
      changefreq,
      priority,
      `Blog post: ${p.slug}`
    );
  });

  return `<?xml version="1.0" encoding="UTF-8"?>
<!-- AUTO-GENERATED by scripts/generate-sitemap.mts — do not edit by hand -->
<!-- Regenerate after any static-route or blog change:
     node --import tsx scripts/generate-sitemap.mts -->
<urlset
  xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://www.sitemaps.org/schemas/sitemap/0.9
                      http://www.sitemaps.org/schemas/sitemap/0.9/sitemap.xsd">
${[...staticEntries, ...blogEntries].join("\n\n")}
</urlset>
`;
}

const xml = build();
fs.writeFileSync(SITEMAP_PATH, xml, "utf-8");
console.log(
  `[sitemap] wrote ${SITEMAP_PATH} with ${STATIC_ROUTES.length} static + ${readBlogPosts().length} blog entries`
);
